### PR TITLE
Remove Braintree alert email

### PR DESCRIPTION
**Pull request by quinnjn**
This email alerts the Braintree team when CI fails

### CODE REVIEW

**Comment by quinnjn** [comment]
@elagarrigue Can this be merged? I got another build email from this repository today.

**Comment by elagarrigue** [comment]
@thuutin

**Comment by quinnjn** [comment]
@elagarrigue and @thuutin any updates on this?

**Comment by thuutin** [comment]
@quinnjn Hi,  I merged it. Sorry for the inconvenience and the late reply :)

**Pull request merged**
